##
# @file derive_secrets.py
# @author Sumedh Girish
# @brief Code generator for HSM cryptographic identities and access control.
#
# **Overview**
#
# This script is the core provisioning utility for the SHIFT HSM. It takes a master
# secrets dictionary (generated during the system build phase) and a user-provided
# permission list to dynamically generate `secrets.c` and `secrets.h`.
#
# **Cryptographic Architecture**
#
# Instead of storing static keys that can be easily extracted from flash memory,
# this framework implements an asymmetric derivation scheme:
# 1.  It compiles group-specific public/private keypairs into the firmware.
# 2.  At runtime, handlers generate ephemeral keys, blinding them using the TRNG.
# 3.  An ECDH shared secret is established between the static device key and the
#     blinded ephemeral key.
# 4.  This shared secret is fed into an ASCON-XOF Key Derivation Function (KDF)
#     along with a domain string ("FS-ASCON-KDF") to produce the final 128-bit
#     AEAD session key.
#
# **Usage Examples:**
#
# ```bash
# # Grant HSM Read/Write for group 0x1234, and Read/Recv for 0x4321
# python3 derive_secrets.py global.secrets 123456 "1234=RW-:4321=R-C"
# ```
#

# flake8: noqa: E731
# pyright: reportAny=false
import argparse
import pickle
from dataclasses import dataclass
from typing import Callable


# -------------------------------  HELPERS  -----------------------------------
def key_as_array(
    groupid: int, secrets: dict[str, dict[str, dict[str, bytes]]], perm: str, sel: str
):
    """
    @brief Format a specific secret as a C-style array initializer list.

    @param groupid (int): The group ID to retrieve.
    @param secrets (dict): The secrets dictionary.
    @param sel (str): The selector ('internal' or 'external').

    @return str: The formatted C array.
    """
    return ", ".join([f"0x{b:02X}" for b in secrets[f"{groupid:04x}"][perm][sel]])


def interrogate_as_array(secrets: dict[str, dict[str, dict[str, bytes]]]):
    return ", ".join([f"0x{b:02X}" for b in secrets["global"]["interrogate"]["value"]])


VALID_PERMS = ("Write", "Read", "Send", "Recv")

# ------------------------------- TEMPLATES -----------------------------------
DISCLAIMER = """\
// ----------------------------------------------------------------------------
//                                   DISCLAIMER
// This file is generated by a utility script. Do not edit this file directly,
//     as it will be overwritten by the script. Instead, view the script to
//   understand how this file is generated and make changes to the script if
//                                   necessary.
// ----------------------------------------------------------------------------
"""

DEFINITIONS = """\
#include "ascon.h"
#include "crypto_aead.h"
#include "filesystem.h"
#include "randombytes.h"
#include "secrets.h"
#include "stubs.h"
#include "ti/devices/msp/msp.h"
#include "uECC.h"
#include <stdint.h>
#include <stddef.h>
#include <string.h>


/**
 * @brief Performs modular multiplication of two scalars (mod n).
 *
 * Used for blinding scalars in the asymmetric master key scheme.
 *
 * @param result Destination buffer (32 bytes).
 * @param left First scalar (32 bytes).
 * @param right Second scalar (32 bytes).
 */
void uECC_mod_mult(uint8_t result[ECC_PRIV_KEYSIZE],
                   const uint8_t left[ECC_PRIV_KEYSIZE],
                   const uint8_t right[ECC_PRIV_KEYSIZE]);

/**
 * @brief Adds a small, random timing delay to decorrelate power traces.
 *
 * Uses the hardware TRNG to wait for a random number of CPU cycles, making
 * it significantly harder for an attacker to align multiple power traces
 * for differential analysis.
 */
static inline void apply_jitter(void) {
    uint32_t r = getrandom32() & 0x3F; // Up to 63 cycles
    for (volatile uint32_t i = 0; i < r; i++) {
        __asm__ volatile ("nop");
    }
}

/**
 * @brief Derives an Ascon AEAD key from an ECC shared secret.
 *
 * This function uses a domain-separated KDF based on Ascon-XOF. It concatenates
 * a domain string ("FS-ASCON-KDF"), the raw shared secret, and a usage string
 * ("AEAD-KEY") before passing them through the XOF. This ensures that the
 * resulting key is cryptographically bound to its intended purpose.
 *
 * @param output Destination buffer for the 16-byte Ascon key.
 * @param sharedKey Raw ECC shared secret (typically 32 bytes).
 * @return KEYS_StatusCode KEYS_OK on success.
 */
static inline void DeriveAsconKey(uint8_t output[ASCON_KEY_SIZE],
                                  uint8_t sharedKey[ECC_PRIV_KEYSIZE])
{
    const uint8_t domain[] = "FS-ASCON-KDF";
    const uint8_t usage[] = "AEAD-KEY";

    uint8_t input[sizeof(domain) - 1 + ECC_PRIV_KEYSIZE + sizeof(usage) - 1];

    size_t offset = 0;
    memcpy(input + offset, domain, sizeof(domain) - 1);
    offset += sizeof(domain) - 1;
    memcpy(input + offset, sharedKey, ECC_PRIV_KEYSIZE);
    offset += ECC_PRIV_KEYSIZE;
    memcpy(input + offset, usage, sizeof(usage) - 1);
    offset += sizeof(usage) - 1;

    ascon_xof_masked(output, ASCON_KEY_SIZE, input, offset);

    /* Wipe intermediate sensitive state */
    memclear(input, offset, 0);
    memclear(sharedKey, ECC_PRIV_KEYSIZE, 0);
}


typedef struct {
    uint8_t nonce[NONCE_SIZE];
    uint8_t masterKey[MASTER_KEY_SIZE];
    uint8_t id[ID_SIZE];
} KeyContext;
"""

HEADER_CONTENT: Callable[[str, int], str] = lambda pin, n_groups: (
    f"""\
#ifndef __SECRETS_H__
#define __SECRETS_H__

#include <stdint.h>
#include "status.h"

#define ECC_PRIV_KEYSIZE 32
#define ECC_PUB_KEYSIZE 64

#define MASTER_PRIV_KEY_SIZE ECC_PRIV_KEYSIZE
#define MASTER_PUB_KEY_SIZE ECC_PUB_KEYSIZE
#define MASTER_KEY_SIZE 16

#define ASCON_KEY_SIZE 16
#define ASCON_TAG_SIZE 16

#define NONCE_SIZE 16
#define ID_SIZE 16

#define HSM_PIN "{pin}"

#define N_RECV_GROUPS {n_groups}
extern const uint16_t recv_groups[{n_groups}];


StatusCode SelectWriteKey(uint16_t groupid, uint8_t output[ASCON_KEY_SIZE]);
StatusCode SelectReadKey(uint16_t groupid, uint8_t output[ASCON_KEY_SIZE]);
StatusCode SelectSendKey(uint16_t groupid, uint8_t output[ASCON_KEY_SIZE]);
StatusCode SelectRecvKey(uint16_t groupid, uint8_t output[ASCON_KEY_SIZE]);

StatusCode SelectInterrogateKey(uint8_t output[ASCON_KEY_SIZE]);
StatusCode SelectReplyKey(uint8_t output[ASCON_KEY_SIZE]);

#endif
"""
)

GEN_WRITEKEY: Callable[[int, dict[str, dict[str, dict[str, bytes]]]], str] = (
    lambda groupid, secrets: (
        f"""\
static StatusCode GenWriteKey_{groupid:04x}(uint8_t key[ASCON_KEY_SIZE])
{{
    KeyContext ctx = {{0}};
    static const uint8_t master_pub[MASTER_PUB_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "write", "master")}
    }};
    static const uint8_t tweak_secret[MASTER_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "write", "tweak")}
    }};

    randombytes(ctx.nonce, NONCE_SIZE);
    memcpy(ctx.id, (uint8_t *) &stage.as.file.metadata.fileid, ID_SIZE);
    memcpy(ctx.masterKey, tweak_secret, MASTER_KEY_SIZE);

    __disable_irq();
    apply_jitter();

    uint8_t s[ECC_PRIV_KEYSIZE];
    if (ascon_xof_masked(s, ECC_PRIV_KEYSIZE, (uint8_t *) &ctx, sizeof(ctx)) != 0)
    {{
        memclear((uint8_t *) &ctx, sizeof(ctx), 0x00);

        __enable_irq();
        return KEYGENERROR;
    }}

    apply_jitter();
    uint8_t eph_priv[ECC_PRIV_KEYSIZE];
    uint8_t eph_pub[ECC_PUB_KEYSIZE];
    if (uECC_make_key(eph_pub, eph_priv) != 1) {{

        memclear((uint8_t *) &ctx, sizeof(ctx), 0);
        memclear(s, ECC_PRIV_KEYSIZE, 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    apply_jitter();
    uint8_t k_blind[ECC_PRIV_KEYSIZE];
    uECC_mod_mult(k_blind, eph_priv, s);

    uint8_t sharedSecret_raw[ECC_PRIV_KEYSIZE];
    if (uECC_shared_secret(master_pub, k_blind, sharedSecret_raw) != 1) {{

        memclear((uint8_t *) &ctx, sizeof(ctx), 0);
        memclear(s, ECC_PRIV_KEYSIZE, 0);
        memclear(eph_priv, ECC_PRIV_KEYSIZE, 0);
        memclear(eph_pub, ECC_PUB_KEYSIZE, 0);
        memclear(k_blind, ECC_PRIV_KEYSIZE, 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    if (key != NULL)
        DeriveAsconKey(key, sharedSecret_raw);

    memcpy((uint8_t *) &stage.as.file.metadata.key, eph_pub, ECC_PUB_KEYSIZE);
    memcpy((uint8_t *) &stage.as.file.metadata.nonce, ctx.nonce, NONCE_SIZE);

    memclear((uint8_t *) &ctx, sizeof(ctx), 0);
    memclear(s, ECC_PRIV_KEYSIZE, 0);
    memclear(eph_priv, ECC_PRIV_KEYSIZE, 0);
    memclear(eph_pub, ECC_PUB_KEYSIZE, 0);
    memclear(k_blind, ECC_PRIV_KEYSIZE, 0);
    memclear(sharedSecret_raw, ECC_PRIV_KEYSIZE, 0);

    __enable_irq();
    return OPWRITE;
}}
"""
    )
)


GEN_READKEY: Callable[[int, dict[str, dict[str, dict[str, bytes]]]], str] = (
    lambda groupid, secrets: (
        f"""\
static StatusCode GenReadKey_{groupid:04x}(uint8_t key[ASCON_KEY_SIZE])
{{
    KeyContext ctx = {{0}};
    static const uint8_t master_priv[MASTER_PRIV_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "read", "master")}
    }};
    static const uint8_t tweak_secret[MASTER_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "read", "tweak")}
    }};

    memcpy(ctx.nonce, (uint8_t *) &stage.as.file.metadata.nonce, NONCE_SIZE);
    memcpy(ctx.id, (uint8_t *) &stage.as.file.metadata.fileid, ID_SIZE);
    memcpy(ctx.masterKey, tweak_secret, MASTER_KEY_SIZE);

    __disable_irq();
    apply_jitter();

    uint8_t s[ECC_PRIV_KEYSIZE];
    if (ascon_xof_masked(s, ECC_PRIV_KEYSIZE, (uint8_t *) &ctx, sizeof(ctx)) != 0) {{
        memclear((uint8_t *) &ctx, sizeof(ctx), 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    apply_jitter();
    uint8_t k_blind[ECC_PRIV_KEYSIZE];
    uECC_mod_mult(k_blind, master_priv, s);

    uint8_t sharedSecret_raw[ECC_PRIV_KEYSIZE];
    if (uECC_shared_secret(
        (uint8_t *) &stage.as.file.metadata.key, k_blind, sharedSecret_raw) != 1)
    {{

        memclear((uint8_t*)&ctx, sizeof(ctx), 0);
        memclear(s, ECC_PRIV_KEYSIZE, 0);
        memclear(k_blind, ECC_PRIV_KEYSIZE, 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    if (key != NULL)
        DeriveAsconKey(key, sharedSecret_raw);

    memclear((uint8_t*)&ctx, sizeof(ctx), 0);
    memclear(s, ECC_PRIV_KEYSIZE, 0);
    memclear(k_blind, ECC_PRIV_KEYSIZE, 0);
    memclear(sharedSecret_raw, ECC_PRIV_KEYSIZE, 0);

    __enable_irq();
    return OPREAD;
}}
"""
    )
)


GEN_SENDKEY: Callable[[int, dict[str, dict[str, dict[str, bytes]]]], str] = (
    lambda groupid, secrets: (
        f"""\
static StatusCode GenSendKey_{groupid:04x}(uint8_t key[ASCON_KEY_SIZE])
{{
    KeyContext ctx = {{0}};
    static const uint8_t peer_pub[MASTER_PUB_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "send", "master")}
    }};
    static const uint8_t tweak_secret[MASTER_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "send", "tweak")}
    }};

    randombytes(ctx.nonce, NONCE_SIZE);
    randombytes(ctx.id, ID_SIZE);
    memcpy(ctx.masterKey, tweak_secret, MASTER_KEY_SIZE);

    __disable_irq();
    apply_jitter();

    uint8_t s[ECC_PRIV_KEYSIZE];
    if (ascon_xof_masked(s, ECC_PRIV_KEYSIZE, (uint8_t *) &ctx, sizeof(ctx)) != 0) {{

        memclear((uint8_t *) &ctx, sizeof(ctx), 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    apply_jitter();
    uint8_t eph_priv[ECC_PRIV_KEYSIZE];
    uint8_t eph_pub[ECC_PUB_KEYSIZE];
    if (uECC_make_key(eph_pub, eph_priv) != 1) {{

        memclear((uint8_t *) &ctx, sizeof(ctx), 0);
        memclear(s, ECC_PRIV_KEYSIZE, 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    apply_jitter();
    uint8_t k_blind[ECC_PRIV_KEYSIZE];
    uECC_mod_mult(k_blind, eph_priv, s);

    uint8_t sharedSecret_raw[ECC_PRIV_KEYSIZE];
    if (uECC_shared_secret(peer_pub, k_blind, sharedSecret_raw) != 1) {{

        memclear((uint8_t *) &ctx, sizeof(ctx), 0);
        memclear(s, ECC_PRIV_KEYSIZE, 0);
        memclear(eph_priv, ECC_PRIV_KEYSIZE, 0);
        memclear(eph_pub, ECC_PUB_KEYSIZE, 0);
        memclear(k_blind, ECC_PRIV_KEYSIZE, 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    if (key != NULL)
        DeriveAsconKey(key, sharedSecret_raw);

    memcpy((uint8_t *) &stage.preamble.key, eph_pub, ECC_PUB_KEYSIZE);
    memcpy((uint8_t *) &stage.preamble.nonce, ctx.nonce, NONCE_SIZE);
    memcpy((uint8_t *) &stage.preamble.mesgid, ctx.id, ID_SIZE);

    memclear((uint8_t *) &ctx, sizeof(ctx), 0);
    memclear(s, ECC_PRIV_KEYSIZE, 0);
    memclear(eph_priv, ECC_PRIV_KEYSIZE, 0);
    memclear(eph_pub, ECC_PUB_KEYSIZE, 0);
    memclear(k_blind, ECC_PRIV_KEYSIZE, 0);
    memclear(sharedSecret_raw, ECC_PRIV_KEYSIZE, 0);

    __enable_irq();
    return OPSEND;
}}
"""
    )
)


GEN_RECVKEY: Callable[[int, dict[str, dict[str, dict[str, bytes]]]], str] = (
    lambda groupid, secrets: (
        f"""\
static StatusCode GenRecvKey_{groupid:04x}(uint8_t key[ASCON_KEY_SIZE])
{{
    KeyContext ctx = {{0}};
    static const uint8_t local_priv[MASTER_PRIV_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "recv", "master")}
    }};
    static const uint8_t tweak_secret[MASTER_KEY_SIZE] = {{
        {key_as_array(groupid, secrets, "recv", "tweak")}
    }};

    memcpy(ctx.nonce, (uint8_t *) &stage.preamble.nonce, NONCE_SIZE);
    memcpy(ctx.id, (uint8_t *) &stage.preamble.mesgid, ID_SIZE);
    memcpy(ctx.masterKey, tweak_secret, MASTER_KEY_SIZE);

    __disable_irq();
    apply_jitter();

    uint8_t s[ECC_PRIV_KEYSIZE];
    if (ascon_xof_masked(s, ECC_PRIV_KEYSIZE, (uint8_t *) &ctx, sizeof(ctx)) != 0) {{

        memclear((uint8_t*)&ctx, sizeof(ctx), 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    apply_jitter();
    uint8_t k_blind[ECC_PRIV_KEYSIZE];
    uECC_mod_mult(k_blind, local_priv, s);

    uint8_t sharedSecret_raw[ECC_PRIV_KEYSIZE];
    if (uECC_shared_secret(
            (uint8_t *) &stage.preamble.key, k_blind, sharedSecret_raw) != 1
       )
    {{

        memclear((uint8_t*)&ctx, sizeof(ctx), 0);
        memclear(s, ECC_PRIV_KEYSIZE, 0);
        memclear(k_blind, ECC_PRIV_KEYSIZE, 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    if (key != NULL)
        DeriveAsconKey(key, sharedSecret_raw);

    memclear((uint8_t*)&ctx, sizeof(ctx), 0);
    memclear(s, ECC_PRIV_KEYSIZE, 0);
    memclear(k_blind, ECC_PRIV_KEYSIZE, 0);
    memclear(sharedSecret_raw, ECC_PRIV_KEYSIZE, 0);

    __enable_irq();
    return OPRECEIVE;
}}
"""
    )
)

GEN_INTERROGATEKEY: Callable[[dict[str, dict[str, dict[str, bytes]]]], str] = (
    lambda secrets: (
        f"""\
StatusCode SelectInterrogateKey(uint8_t output[ASCON_KEY_SIZE])
{{
    KeyContext derivation_ctx = {{0}};
    static const uint8_t master_secret[MASTER_KEY_SIZE] = {{
        {interrogate_as_array(secrets)}
    }};

    __disable_irq();
    apply_jitter();

    memcpy(derivation_ctx.masterKey, master_secret, MASTER_KEY_SIZE);
    memcpy(derivation_ctx.nonce, (uint8_t *) &stage.preamble.nonce, NONCE_SIZE);
    memcpy(derivation_ctx.id, (uint8_t *) &stage.preamble.mesgid, ID_SIZE);

    if (ascon_xof_masked(
        output, ASCON_KEY_SIZE, (uint8_t*)&derivation_ctx, sizeof(derivation_ctx)
        ) != 0
    )
    {{
        memclear((uint8_t *) &derivation_ctx, sizeof(KeyContext), 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    memclear(&derivation_ctx, sizeof(derivation_ctx), 0);

    __enable_irq();
    return OPINTERROGATE;
}}
"""
    )
)

GEN_REPLYKEY: Callable[[dict[str, dict[str, dict[str, bytes]]]], str] = lambda secrets: (
    f"""\
StatusCode SelectReplyKey(uint8_t output[ASCON_KEY_SIZE])
{{
    KeyContext derivation_ctx = {{0}};
    static const uint8_t master_secret[MASTER_KEY_SIZE] = {{
        {interrogate_as_array(secrets)}
    }};

    __disable_irq();
    apply_jitter();

    memcpy(derivation_ctx.masterKey, master_secret, MASTER_KEY_SIZE);
    memcpy(derivation_ctx.nonce, (uint8_t *) &stage.preamble.nonce, NONCE_SIZE);
    memcpy(derivation_ctx.id, (uint8_t *) &stage.preamble.mesgid, ID_SIZE);

    if (ascon_xof_masked(
        output, ASCON_KEY_SIZE, (uint8_t*)&derivation_ctx, sizeof(derivation_ctx)
        ) != 0
    )
    {{
        memclear((uint8_t *) &derivation_ctx, sizeof(KeyContext), 0);

        __enable_irq();
        return KEYGENERROR;
    }}

    memclear(&derivation_ctx, sizeof(derivation_ctx), 0);
    __enable_irq();
    return OPREPLY;
}}
"""
)

GEN_STUB: Callable[[], str] = lambda: (
    """\
static StatusCode GenStub(void)
{
    return PERMISSIONERROR;
}
"""
)

GEN_CASE_SMT: Callable[[int, str], str] = lambda groupid, permstr: (
    f"""\
    case 0x{groupid:04x}:
        return Gen{permstr}Key_{groupid:04x}(key);
    """
)

GEN_CASE_STUB: Callable[[int], str] = lambda groupid: (
    f"""\
    case 0x{groupid:04x}:
        return GenStub();
    """
)

CASELIST: Callable[[str, str], str] = lambda permstr, cases: (
    f"""\
StatusCode Select{permstr}Key(uint16_t groupid, uint8_t key[ASCON_KEY_SIZE])
{{
    switch (groupid) {{
{cases}
    default:
        return GenStub();
    }}
}}
"""
)

RECV_GROUPS: Callable[[list[int]], str] = lambda groups: (
    f"""\
const uint16_t recv_groups[{len(groups)}] = {{
    {", ".join(sorted([f"0x{g:04x}" for g in groups]))}
}};
"""
)


# ---------------------------------- CLI --------------------------------------
@dataclass
class Permission:
    """
    @brief Represents permissions for a specific group.

    @param group_id (int): The 16-bit group identifier.
    @param read (bool): Permission to read files in this group.
    @param write (bool): Permission to write files in this group.
    @param receive (bool): Permission to receive files from peers for this group.
    """

    group_id: int = 0
    read: bool = False
    write: bool = False
    receive: bool = False

    @classmethod
    def deserialize(cls, perms: str):
        group_id, perm_string = perms.split("=")

        perm_obj = cls(
            int(group_id, 16),
            read=perm_string[0] == "R",
            write=perm_string[1] == "W",
            receive=perm_string[2] == "C",
        )
        return perm_obj

    def serialize(self):
        ret = f"{self.group_id:04x}="
        prepr: dict[str, str] = {"read": "R", "write": "W", "receive": "C"}
        for perm, shorthand in prepr.items():
            ret += shorthand if getattr(self, perm) else "-"
        return ret


class PermissionList(list[Permission]):
    """
    @brief A collection of Permission objects with serialization support.
    """

    def __init__(self, *args: Permission):
        super().__init__()
        for item in args:
            self.append(item)

    @classmethod
    def deserialize(cls, perms: str):
        ret = cls()
        permissions_strings = perms.split(":")
        for entry in permissions_strings:
            perm_obj = Permission.deserialize(entry)
            ret.append(perm_obj)
        return ret

    def serialize(self):
        return ":".join(perm.serialize() for perm in self)


# ---------------------------------- GEN --------------------------------------


def generateCaseList(permission: str, permissionlist: PermissionList):
    """
    @brief Generates a C switch-case block for selecting the correct key derivation
    routine based on group ID and the requested operation.

    @param permission (str): The permission type (Read, Write, etc.).
    @param permissionlist (PermissionList): The list of permissions.

    @return str: The generated C code.
    """
    assert permission in VALID_PERMS, "Invalid permission passed to genCaseList"

    validgen: Callable[[int], str] = lambda groupid: GEN_CASE_SMT(groupid, permission)
    stubgen: Callable[[int], str] = GEN_CASE_STUB

    genmap: Callable[[Permission], dict[str, bool]] = lambda p: dict(
        zip(VALID_PERMS, (p.write, p.read, True, p.receive))
    )
    cases = [
        validgen(p.group_id) if genmap(p)[permission] else stubgen(p.group_id)
        for p in permissionlist
    ]

    return CASELIST(permission, "\n".join(cases))


def generateSecrets(
    outfilename: str,
    permissionlist: PermissionList,
    secrets: dict[str, dict[str, dict[str, bytes]]],
):
    """
    @brief Compiles all derived key routines and lookup tables into a single C source file.

    @param outfilename (str): The output file path.
    @param permissionlist (PermissionList): The list of permissions.
    @param secrets (dict): The master secrets.
    """
    builder = [
        DISCLAIMER,
        DEFINITIONS,
        RECV_GROUPS([p.group_id for p in permissionlist if p.receive]),
        GEN_STUB(),
    ]

    for p in permissionlist:
        if p.write:
            builder.append(GEN_WRITEKEY(p.group_id, secrets))
        if p.read:
            builder.append(GEN_READKEY(p.group_id, secrets))
        if p.receive:
            builder.append(GEN_RECVKEY(p.group_id, secrets))
        builder.append(GEN_SENDKEY(p.group_id, secrets))

    builder.append(GEN_INTERROGATEKEY(secrets))
    builder.append(GEN_REPLYKEY(secrets))

    builder.append(generateCaseList("Write", permissionlist))
    builder.append(generateCaseList("Read", permissionlist))
    builder.append(generateCaseList("Recv", permissionlist))
    builder.append(generateCaseList("Send", permissionlist))

    with open(outfilename, "w") as outfile:
        _ = outfile.write("\n\n".join(builder))


def arg_parse() -> argparse.Namespace:
    """
    @brief Defines and parses command line arguments for secret derivation.

    @return argparse.Namespace: The parsed arguments.
    """
    parser = argparse.ArgumentParser()

    _ = parser.add_argument(
        "secrets", type=argparse.FileType("rb"), help="Path to secrets file"
    )
    _ = parser.add_argument("hsm_pin", type=str, help="User PIN for the HSM")
    _ = parser.add_argument(
        "permissions",
        type=str,
        help='List of colon-separated permissions. E.g., "1234=R--:4321=RWC"',
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = arg_parse()

    secrets = pickle.load(args.secrets)
    permissions = PermissionList.deserialize(args.permissions)

    assert len(args.hsm_pin) == 6, "Invalid pin length"
    generateSecrets("secrets/secrets.c", permissions, secrets)

    with open("secrets/secrets.h", "w") as headerfile:
        _ = headerfile.write(
            DISCLAIMER
            + "\n\n"
            + HEADER_CONTENT(args.hsm_pin, len([g for g in permissions if g.receive]))
        )


# -----------------------------------------------------------------------------
